language: generic
sudo: required
services:
  - docker

before_install:
  - docker build  -t ankur0405/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ankur0405/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-109816836354"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_key